apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS app_db;
    GRANT ALL PRIVILEGES ON app_db.* TO 'app_user'@'%';
    USE app_db;
    CREATE TABLE counter (
      id INT_AUTO_INCREMENT PRIMARY_KEY,
      value INT
    );